modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Technici4n/Modern-Dynamics"
displayURL="https://www.curseforge.com/minecraft/mc-mods/modern-dynamics"
logoFile="assets/moderndynamics/mdlogo.png"
authors="Technici4n"
license="LGPLv3"

[[mods]]
modId="moderndynamics"
version="${version}"
displayName="Modern Dynamics"
description="Modern item, fluid and energy transport Minecraft mod."

[[mixins]]
config="moderndynamics.mixins.json"

[[dependencies.moderndynamics]]
modId="neoforge"
type="REQUIRED"
versionRange="[21.1.169,)"
ordering="NONE"
side="BOTH"
